sudo: required
services:
  - docker

before_install:
  - docker build -t tomntomson/docker-react -f Dockerfile.dev ./

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-558101299498"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
