sudo: required
services:
  - docker

before_install:
  - docker build -t tomntomson/docker-react -f Dockerfile.dev ./

script:
  - docker run tomntomson/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region:

